#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Usage:
  nb -l
  nb <message>
  nb -h

Options:
  -f <file>   use this file [default: /media/sf_vagrant-root/log]
  -l          list all previous logs
  -h          show this help screen
"""

import os
import logging
import docopt

args = docopt.docopt(__doc__)

more = 'less'

if args['-l']:
    os.execlp(more, more, args['-f'])

logging.basicConfig(format='%(asctime)s %(message)s',
                    level=logging.INFO, filename=args['-f'])
logging.info(args['<message>'])
